[package]
name = "pixelrust"
version = "0.1.0"
authors = ["commodor64", "galoz666"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.1"
imageproc = "0.18.0"
edge-detection = "0.2.3"